spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

logging:
    level:
      root: INFO
      springframework: INFO
      com.eliab.sistemas.sgp: INFO